# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: continuous-integration-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root  
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: gopher_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - name: Checkout the code repo from main branch
      uses: actions/checkout@v4

    - name: Set up Go runtime
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - name: Install migrate package
      run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

    - name: Run migrations
      run: make migrateup

    - name: Test execution - Build and Test
      run: make test
